export interface Employee {
  employee_id: string;
  first_name: string;
  middle_name: string | null;
  last_name: string;
  suffix: string | null;
  address: string | null;
  city: string | null;
  province: string | null;
  zip: string | null;
  location: string | null;
  department: string | null;
  project: string | null;
  team: string | null;
  position: string | null;
  employment: string | null;
  user_profile: string | null;
  manager: string | null;
  vendor: string | null;
  email: string | null;
  phone: string | null;
  ctc: string | null;
  ctc_place: string | null;
  ctc_date: string | null | Date;
  ctc_amount_paid: number | null;
  notes: string | null;
  pay_freq: string | null;
  sex: string | null;
  active: boolean;
  birthday: string | null | Date;
  date_hired: string | null | Date;
  kasambahay: boolean;
  regularized: string | null | Date;
  separated: string | null | Date;
  contract_start: string | null | Date;
  contract_end: string | null | Date;
  minimum_earner: boolean;
  minimum_daily: number | null;
  minimum_monthly: number | null;
  tax_id: string | null;
  tax_witheld: boolean;
  sss_gsis: string | null;
  sss_gsis_witheld: boolean;
  phic_id: string | null;
  phic_witheld: boolean;
  hdmf_id: string | null;
  hdmf_witheld: boolean;
  hdmf_account: string | null;
  bank: string | null;
  bank_account: string | null;
  rate_type: string | null;
  base_monthly_pay: number | null;
  days_per_month: number | null;
  hours_per_day: number | null;
  daily_rate: number | null;
  hourly_rate: number | null;
  col_allowance: number | null;
  represent_allowance: number | null;
  housing_allowance: number | null;
  transportation_allowance: number | null;
  created_at?: string | Date;
  updated_at?: string | Date;
  id?: string;
}
